"""
Goal Tools for LangGraph agents.

These tools allow agents to create, update, and manage goals.
"""

from typing import Dict, Any, List, Optional
from datetime import datetime
import uuid

from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession

from app.core.database import AsyncSessionLocal
from app.models import Goal, GoalStatus, GoalPriority
from app.agents.tools.rag_tools import get_similar_goals, RAGTools


async def create_goal_tool(
    user_id: str,
    title: str,
    description: str,
    course_id: Optional[str] = None,
    priority: str = "medium",
    validation_criteria: Optional[List[str]] = None,
    ai_generated: bool = True,
    use_rag: bool = True
) -> Dict[str, Any]:
    """
    Create a new goal, optionally using RAG for context.

    Args:
        user_id: User ID
        title: Goal title
        description: Goal description
        course_id: Optional course ID
        priority: low, medium, high, urgent
        validation_criteria: List of validation criteria
        ai_generated: Whether goal was generated by AI
        use_rag: Whether to use RAG for context

    Returns:
        Dict with created goal info

    Example:
        >>> goal = await create_goal_tool(
        ...     user_id="usr_123",
        ...     title="Learn FastAPI",
        ...     description="Build a complete REST API with FastAPI",
        ...     priority="high"
        ... )
    """
    # Use RAG to get similar goals for context
    rag_context = None
    if use_rag:
        similar_goals = await get_similar_goals(
            query=f"{title}. {description}",
            user_id=user_id,
            limit=3,
            only_completed=True
        )
        rag_context = {
            "similar_goals_count": len(similar_goals),
            "similar_goals": [
                {
                    "title": g["title"],
                    "similarity": g["similarity"]
                }
                for g in similar_goals
            ]
        }

    # Create goal
    goal_id = str(uuid.uuid4())

    async with AsyncSessionLocal() as db:
        goal = Goal(
            id=goal_id,
            user_id=user_id,
            course_id=course_id,
            title=title,
            description=description,
            status=GoalStatus.PENDING,
            priority=GoalPriority[priority.upper()],
            progress_percentage=0.0,
            ai_generated=ai_generated,
            validation_criteria={
                "criteria": validation_criteria or []
            } if validation_criteria else None,
            metadata={
                "rag_context": rag_context,
                "created_by_agent": True
            }
        )

        db.add(goal)
        await db.commit()
        await db.refresh(goal)

        # Generate and save embedding
        if description:
            rag = RAGTools()
            from app.models import Embedding

            embedding_vector = await rag._generate_embedding(
                f"{title}\n\n{description}"
            )

            embedding = Embedding(
                id=str(uuid.uuid4()),
                user_id=user_id,
                entity_type="goal",
                entity_id=goal_id,
                content=f"Goal: {title}\n\nDescription: {description}",
                embedding=embedding_vector,
                model="text-embedding-3-small",
                metadata={"goal_status": goal.status.value}
            )

            db.add(embedding)
            await db.commit()

        return {
            "goal_id": goal.id,
            "title": goal.title,
            "description": goal.description,
            "status": goal.status.value,
            "priority": goal.priority.value,
            "ai_generated": goal.ai_generated,
            "rag_context": rag_context,
            "created_at": goal.created_at.isoformat()
        }


async def update_goal_tool(
    goal_id: str,
    user_id: str,
    status: Optional[str] = None,
    progress_percentage: Optional[float] = None,
    metadata: Optional[Dict[str, Any]] = None
) -> Dict[str, Any]:
    """
    Update an existing goal.

    Args:
        goal_id: Goal ID to update
        user_id: User ID (for authorization)
        status: New status (pending, in_progress, completed, blocked, cancelled)
        progress_percentage: Progress 0-100
        metadata: Additional metadata to merge

    Returns:
        Updated goal info
    """
    async with AsyncSessionLocal() as db:
        # Get goal
        result = await db.execute(
            select(Goal).where(
                Goal.id == goal_id,
                Goal.user_id == user_id
            )
        )
        goal = result.scalar_one_or_none()

        if not goal:
            return {"error": "Goal not found"}

        # Update fields
        if status:
            goal.status = GoalStatus[status.upper()]

            # Set timestamps
            if status == "in_progress" and not goal.started_at:
                goal.started_at = datetime.utcnow()
            elif status == "completed" and not goal.completed_at:
                goal.completed_at = datetime.utcnow()
                goal.progress_percentage = 100.0

        if progress_percentage is not None:
            goal.progress_percentage = min(100.0, max(0.0, progress_percentage))

        if metadata:
            current_metadata = goal.metadata or {}
            current_metadata.update(metadata)
            goal.metadata = current_metadata

        goal.updated_at = datetime.utcnow()

        await db.commit()
        await db.refresh(goal)

        return {
            "goal_id": goal.id,
            "title": goal.title,
            "status": goal.status.value,
            "progress_percentage": goal.progress_percentage,
            "updated_at": goal.updated_at.isoformat()
        }


async def list_goals_tool(
    user_id: str,
    status: Optional[str] = None,
    course_id: Optional[str] = None,
    limit: int = 10
) -> List[Dict[str, Any]]:
    """
    List goals for a user.

    Args:
        user_id: User ID
        status: Optional status filter
        course_id: Optional course filter
        limit: Max results

    Returns:
        List of goals
    """
    async with AsyncSessionLocal() as db:
        query = select(Goal).where(Goal.user_id == user_id)

        if status:
            query = query.where(Goal.status == GoalStatus[status.upper()])

        if course_id:
            query = query.where(Goal.course_id == course_id)

        query = query.order_by(Goal.created_at.desc()).limit(limit)

        result = await db.execute(query)
        goals = result.scalars().all()

        return [
            {
                "goal_id": goal.id,
                "title": goal.title,
                "description": goal.description,
                "status": goal.status.value,
                "priority": goal.priority.value,
                "progress_percentage": goal.progress_percentage,
                "ai_generated": goal.ai_generated,
                "created_at": goal.created_at.isoformat(),
                "course_id": goal.course_id
            }
            for goal in goals
        ]
